<?php //-->
/**
 * This file is part of the Handlebars PHP Template Engine.
 *
 * Copyright and license information can be found at LICENSE.txt
 * distributed with this package.
 */

namespace HandlebarsPHP;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 02:11:00.
 */
class Tokenizer_Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var Tokenizer
     */
    protected $object;

    /**
     * @var string
     */
    protected $source;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->source = file_get_contents(__DIR__.'/assets/tokenizer.html');
        $this->object = new Tokenizer($this->source);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers HandlebarsPHP\Tokenizer::__construct
     */
    public function test__construct()
    {
        $actual = $this->object->__construct($this->source);

        $this->assertNull($actual);
    }

    /**
     * @covers HandlebarsPHP\Tokenizer::tokenize
     * @covers HandlebarsPHP\Tokenizer::addNode
     * @covers HandlebarsPHP\Tokenizer::flushText
     * @covers HandlebarsPHP\Tokenizer::findVariable
     */
    public function testTokenize()
    {
        $i = 0;

        //should we test for more?
        $tests = array(
            '<div class="product-fields">
    <div class="form-group',
        "if errors.product_title",
        ' has-error',
        "if",
        ' clearfix">
        <label class="control-label">',
            "_ 'Title'",
            '</label>
        <div>
            <input
                type="text"
                class="form-control"
                name="product_title"
                placeholder="',
            "_ 'What is the name of this product?'",
            '"
                value="',
            "item.product_title",
            '" />

            ',
            "if errors.product_title",
            '
            <span class="help-text text-danger">',
            "errors.product_title",
            '</span>
            ',
            "if",
            '
        </div>
    </div>

    <div class="form-group'
        );

        $unit = $this;

        $this->object->tokenize(function($node) use ($unit, $tests, &$i) {
            if(isset($tests[$i])) {
                $unit->assertEquals($tests[$i], $node['value']);
            }

            $i++;
        });
    }
}
